### PR TITLE
added spacy.pipe() batch support

### PR DESCRIPTION
**Pull request by davidberenstein1957**

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
https://hacktoberfest.com/participation/#pr-mr-details

**Comment by davidberenstein1957** [comment]
https://hacktoberfest.com/participation/#pr-mr-details

**Comment by MartinoMensio** [comment]
Hi @davidberenstein1957 ,
Thank you very much for your PR! Your contribution is really appreciated!

I am going to analyse it and do some tests, but it looks great! 😎
And I am adding this repo to Hacktoberfest too!

Cheers,
Martino

**Comment by MartinoMensio** [comment]
Hi @davidberenstein1957 ,
I had to make some minor changes to remove some replicated code for error handling and easier-to-understand pooling that preserves the ordering of the documents (on their own futures.as_completed does not, and it requires that external dict which could cause some issues).
But otherwise, your PR is really good. 
I added some tests and it seems to be working well.

Approved for merging!

**Comment by davidberenstein1957** [comment]
@MartinoMensio I think you need to add the "hacktoberfest-accepted" label to this PR.
image

**Comment by davidberenstein1957** [comment]
Great to hear that Martin! I could have also used other ways to speed-up the requests, but I felt core Python without using actual async would be the least invasive way to implement this.

Regards,
David

**Pull request merged**
